spring.application.name=web-flux-demo
#spring.config.import=file:.env[.properties]

# HiveMQ MQTT connection
MQTT_HOST=${MQTT_HOST:localhost}
MQTT_PORT=${MQTT_PORT:8883}
MQTT_USER=${MQTT_USER:guest}
MQTT_PASSWORD=${MQTT_PASSWORD:guest}

# Logging
logging.level.root=INFO
logging.level.org.demo.webfluxdemo=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
