name: Satellite CI workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
    tests:
      runs-on: ubuntu-latest
      container:
        image: maven:3.9.8-eclipse-temurin-21
      steps:
        - uses: actions/checkout@v3

        - name: Run tests
          run: mvn -B -Dstyle.color=always test
    build:
      runs-on: ubuntu-latest
      container:
        image: maven:3.9.8-eclipse-temurin-21
      steps:
        - uses: actions/checkout@v3

        - name: Build JAR
          run: mvn -B -DskipTests -Dstyle.color=always  package

